HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 0
Cache-Control: private
Connection: keep-alive
Content-Type: application/json
Date: Tue, 05 Jan 2016 12:53:10 GMT
Server: nginx/1.4.6 (Ubuntu)
Via: 1.1 varnish-v4
X-Powered-By: PHP/5.5.9-1ubuntu4.14
X-Varnish: 5160398
transfer-encoding: chunked

{"id":140770,"hash":"4d78aAa0","title":"Aller anfang ist schwer","popularity":null,"album":{"name":"Berlin Eggsile"},"artist":{"name":"L'oeuf Raide"},"duration":242,"reference":"45495","isrc":"FR92U0900760","year":null}