HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 26 Mar 2015 19:46:16 GMT
Content-Type: application/json
Content-Length: 165
Connection: keep-alive
X-Powered-By: PHP/5.5.9-1ubuntu4.5
Cache-Control: private, must-revalidate
pragma: no-cache
expires: -1

{}
