HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 0
Cache-Control: max-age=86400, public, s-maxage=86400
Connection: keep-alive
Content-Length: 224
Content-Type: application/json
Date: Tue, 05 Jan 2016 14:46:41 GMT
Server: nginx/1.4.6 (Ubuntu)
Via: 1.1 varnish-v4
X-Powered-By: PHP/5.5.9-1ubuntu4.14
X-Varnish: 5104642

[{"id":187069,"hash":"16E5a170","title":"Dahoim isch Dahoim","popularity":null,"album":{"name":"Zsamma besser dran"},"artist":{"name":"So Semmer Halt"},"duration":602,"external_id":"88988","isrc":"DEE841425050","year":null}]